const TYPES=['scene','action','character','dialogue','parenthetical','transition'];
const LABELS={scene:'Scene Heading',action:'Action',character:'Character',dialogue:'Dialogue',parenthetical:'Parenthetical',transition:'Transition'};
const pagesEl=document.getElementById('pages'), sceneList=document.getElementById('sceneList');
const nameEl=document.getElementById('scriptName'), sceneStat=document.getElementById('sceneStat'), wordStat=document.getElementById('wordStat'), pageStat=document.getElementById('pageStat'), saveStatus=document.getElementById('saveStatus');
let state={title:'ಹೊಸ ಚಿತ್ರಕಥೆ',author:'',blocks:[{type:'scene',text:''}]}; let activeBlock=null; let saveTimer;
function newPage(){const p=document.createElement('section');p.className='page';p.innerHTML='<div class="page-inner"></div><div class="page-number"></div>';pagesEl.appendChild(p);return p}
function newBlock(type='action',text=''){const b=document.createElement('div');b.className='block';b.dataset.type=type;b.contentEditable='true';b.spellcheck=false;b.textContent=text||'';b.dataset.placeholder=text?'':' ';b.addEventListener('focus',()=>{activeBlock=b;setActiveType(type)});b.addEventListener('input',()=>{ensurePagination();scheduleSave();});b.addEventListener('keydown',blockKey);return b}
function render(){pagesEl.innerHTML='';const p=newPage();let inner=p.querySelector('.page-inner');state.blocks.forEach((x,i)=>{let b=newBlock(x.type,x.text);inner.appendChild(b);if(i===0){activeBlock=b}});ensurePagination();updateStats();if(activeBlock){activeBlock.focus();setActiveType(activeBlock.dataset.type)}}
function contentHeight(inner){return inner.clientHeight}
function overflows(b){const inner=b.parentElement;return b.offsetTop+b.offsetHeight>inner.clientHeight-2}
function splitBlock(b){const txt=b.textContent||'';if(txt.length<40)return false;let lo=1,hi=txt.length,best=1;const inner=b.parentElement;const original=txt;while(lo<=hi){let mid=(lo+hi)>>1;b.textContent=original.slice(0,mid);if(!overflows(b)){best=mid;lo=mid+1}else hi=mid-1}let cut=best;while(cut>1 && !/\s/.test(original[cut-1]))cut--;if(cut<20)cut=best;b.textContent=original.slice(0,cut).trimEnd();const rest=original.slice(cut).trimStart();const next=b.nextElementSibling;if(next&&next.dataset.type===b.dataset.type&&next.classList.contains('block'))next.textContent=rest+' '+next.textContent;else{const nb=newBlock(b.dataset.type,rest);b.parentElement.appendChild(nb)}return true}
function moveOverflowForward(){let changed=false;const pages=[...pagesEl.querySelectorAll('.page')];for(let i=0;i<pages.length;i++){const inner=pages[i].querySelector('.page-inner');let blocks=[...inner.querySelectorAll('.block')];for(const b of blocks){if(!overflows(b))continue;if(splitBlock(b)){changed=true;continue}let next=pages[i+1]||newPage();next.querySelector('.page-inner').prepend(b);changed=true;}}return changed}
function ensurePagination(){let guard=0;while(guard++<30){if(!moveOverflowForward())break}cleanupEmptyPages();numberPages();syncStateFromDom();updateStats()}
function cleanupEmptyPages(){const pages=[...pagesEl.querySelectorAll('.page')];pages.slice(1).forEach(p=>{if(!p.querySelector('.block'))p.remove()})}
function numberPages(){[...pagesEl.querySelectorAll('.page')].forEach((p,i)=>p.querySelector('.page-number').textContent=i+1)}
function syncStateFromDom(){const blocks=[...pagesEl.querySelectorAll('.block')].map(b=>({type:b.dataset.type,text:b.textContent}));state.blocks=blocks.length?blocks:[{type:'scene',text:''}]}
function updateStats(){const blocks=[...pagesEl.querySelectorAll('.block')];const scenes=blocks.filter(b=>b.dataset.type==='scene').length;const words=blocks.reduce((n,b)=>n+(b.textContent.trim()?b.textContent.trim().split(/\s+/).length:0),0);sceneStat.textContent=`${scenes} scene${scenes===1?'':'s'}`;wordStat.textContent=`${words} word${words===1?'':'s'}`;const n=pagesEl.querySelectorAll('.page').length;pageStat.textContent=`${n} page${n===1?'':'s'}`}
function setActiveType(type){document.querySelectorAll('.format').forEach(x=>x.classList.toggle('active',x.dataset.type===type))}
function setType(type){if(!activeBlock)return;activeBlock.dataset.type=type;activeBlock.focus();setActiveType(type);scheduleSave()}
function nextType(dir=1){if(!activeBlock)return;let i=TYPES.indexOf(activeBlock.dataset.type);setType(TYPES[(i+dir+TYPES.length)%TYPES.length])}
function blockKey(e){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveLocal();return}if(e.key==='Tab'){e.preventDefault();nextType(e.shiftKey?-1:1);return}if(e.key==='Enter'){e.preventDefault();const nb=newBlock('action','');activeBlock.insertAdjacentElement('afterend',nb);nb.focus();activeBlock=nb;setActiveType('action');setTimeout(ensurePagination,0);return}if(e.key==='Backspace'&&activeBlock.textContent===''&&activeBlock.previousElementSibling){e.preventDefault();const prev=activeBlock.previousElementSibling;activeBlock.remove();prev.focus();activeBlock=prev;ensurePagination()}}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveLocal,400)}
function saveLocal(){syncStateFromDom();state.title=nameEl.value||'ಹೊಸ ಚಿತ್ರಕಥೆ';localStorage.setItem('writerBroKannada',JSON.stringify(state));saveStatus.textContent='Saved locally • '+new Date().toLocaleTimeString('kn-IN',{hour:'2-digit',minute:'2-digit'});}
function loadLocal(){try{const x=JSON.parse(localStorage.getItem('writerBroKannada'));if(x&&Array.isArray(x.blocks)){state=x;nameEl.value=x.title||'ಹೊಸ ಚಿತ್ರಕಥೆ'}}catch(e){}}
function download(){syncStateFromDom();state.title=nameEl.value;const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.title||'writer-bro-script').replace(/[^\w\u0C80-\u0CFF -]/g,'')+'.wbs';a.click();URL.revokeObjectURL(a.href)}
function openFile(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.blocks){state=x;nameEl.value=x.title||'ಹೊಸ ಚಿತ್ರಕಥೆ';render();saveLocal()}}catch(e){alert('Invalid .wbs file')}};r.readAsText(file)}
document.querySelectorAll('.format').forEach(b=>b.addEventListener('click',()=>setType(b.dataset.type)));
document.getElementById('newBtn').onclick=()=>{if(confirm('ಹೊಸ ಚಿತ್ರಕಥೆ ಪ್ರಾರಂಭಿಸಬೇಕೆ?')){state={title:'ಹೊಸ ಚಿತ್ರಕಥೆ',author:'',blocks:[{type:'scene',text:''}]};nameEl.value=state.title;localStorage.removeItem('writerBroKannada');render()}};
document.getElementById('saveBtn').onclick=saveLocal;document.getElementById('downloadBtn').onclick=download;document.getElementById('printBtn').onclick=()=>window.print();
document.getElementById('shortcutsBtn').onclick=()=>document.getElementById('shortcuts').classList.remove('hidden');document.getElementById('closeShortcuts').onclick=()=>document.getElementById('shortcuts').classList.add('hidden');document.getElementById('shortcuts').onclick=e=>{if(e.target.id==='shortcuts')e.target.classList.add('hidden')};
document.getElementById('focusBtn').onclick=()=>document.body.classList.toggle('focus-mode');nameEl.addEventListener('input',()=>{state.title=nameEl.value;scheduleSave()});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&['1','2','3','4','5','6'].includes(e.key)){e.preventDefault();setType(TYPES[+e.key-1])}});
// Scene navigator
function renderScenes(){sceneList.innerHTML='';[...pagesEl.querySelectorAll('.block[data-type=scene]')].forEach((b,i)=>{const d=document.createElement('div');d.className='scene';d.innerHTML=`<span class="scene-num">${i+1}</span>${b.textContent.trim()||'ಹೊಸ ದೃಶ್ಯ'}`;d.onclick=()=>{b.scrollIntoView({behavior:'smooth',block:'center'});b.focus()};sceneList.appendChild(d)})}
const oldUpdate=updateStats;updateStats=function(){oldUpdate();renderScenes()};
loadLocal();render();
