// Writer Bro — Kannada-first screenplay editor
const BLOCK_TYPES=['scene','action','character','dialogue','parenthetical','transition'];
const NEXT={scene:'action',action:'character',character:'dialogue',dialogue:'action',parenthetical:'dialogue',transition:'scene'};
const LABELS={scene:'SCENE',action:'ACTION',character:'CHARACTER',dialogue:'DIALOGUE',parenthetical:'PAREN',transition:'TRANSITION'};
const PLACEHOLDERS={scene:'INT./EXT. ಸ್ಥಳ — ಸಮಯ',action:'ದೃಶ್ಯ ವಿವರಣೆ...',character:'ಪಾತ್ರದ ಹೆಸರು',dialogue:'ಸಂಭಾಷಣೆ...',parenthetical:'(ಭಾವ / ನಿರ್ದೇಶನ)',transition:'CUT TO:'};
const AUTOSAVE=20000;
let state={title:'ಅಶೀರ್ಷಿಕೆ',author:'',blocks:[],idSeq:0,dirty:false,currentScriptKey:null};
let focusedBlockId=null, autosaveTimer=null, paginationFrame=null;

function nextId(){return 'b'+(++state.idSeq)}
function addBlock(type='action',text='',afterId=null){const b={id:nextId(),type,text}; if(afterId){const i=state.blocks.findIndex(x=>x.id===afterId);state.blocks.splice(i+1,0,b)}else state.blocks.push(b);state.dirty=true;return b.id}
function updateBlock(id,patch){const b=state.blocks.find(x=>x.id===id);if(b){Object.assign(b,patch);state.dirty=true}}
function removeBlock(id){const i=state.blocks.findIndex(x=>x.id===id);if(i<0)return null;state.blocks.splice(i,1);state.dirty=true;return state.blocks[Math.max(0,i-1)]?.id||null}
function before(id){const i=state.blocks.findIndex(x=>x.id===id);return i>0?state.blocks[i-1]:null}
function wordCount(){return state.blocks.reduce((n,b)=>n+(b.text.trim()?b.text.trim().split(/\s+/).length:0),0)}
function renderMeta(){document.title=(state.dirty?'● ':'')+(state.title||'ಅಶೀರ್ಷಿಕೆ')+' — Writer Bro';document.getElementById('statScenes').textContent=`${state.blocks.filter(b=>b.type==='scene').length} scenes`;document.getElementById('statWords').textContent=`${wordCount()} words`;document.getElementById('statPages').textContent=`${Math.max(1,document.querySelectorAll('.script-page').length)} pages`;document.getElementById('saveStatus').textContent=state.dirty?'Unsaved changes':'Saved locally'}
function makeBlock(b){const el=document.createElement('div');el.className=`script-block block-${b.type}`;el.dataset.blockId=b.id;el.dataset.type=b.type;const badge=document.createElement('div');badge.className='block-badge';badge.textContent=LABELS[b.type];const ta=document.createElement('textarea');ta.className='block-content';ta.value=b.text;ta.placeholder=PLACEHOLDERS[b.type];ta.rows=1;ta.lang='kn';ta.spellcheck=false;ta.addEventListener('focus',()=>{focusedBlockId=b.id;setActiveType(b.type)});ta.addEventListener('input',()=>{autoResize(ta);updateBlock(b.id,{text:ta.value});renderScenes();renderMeta();scheduleAutosave();queuePagination(b.id)});ta.addEventListener('keydown',e=>handleKey(e,b.id,ta));el.append(badge,ta);requestAnimationFrame(()=>autoResize(ta));return el}
function autoResize(ta){ta.style.height='auto';ta.style.height=Math.max(23,ta.scrollHeight)+'px'}
function pageTemplate(index){const p=document.createElement('article');p.className='script-page';if(index===0){const meta=document.createElement('div');meta.className='page-meta';const title=document.createElement('input');title.id='pageTitleInput';title.className='page-title-input';title.value=state.title;title.placeholder='ಶೀರ್ಷಿಕೆಯಿಲ್ಲ';title.addEventListener('input',e=>{state.title=e.target.value;document.getElementById('titleInput').value=state.title;state.dirty=true;renderMeta();scheduleAutosave()});const author=document.createElement('input');author.id='pageAuthorInput';author.className='page-author-input';author.value=state.author;author.placeholder='ಬರೆದವರು';author.addEventListener('input',e=>{state.author=e.target.value;state.dirty=true;scheduleAutosave()});meta.append(title,author);p.appendChild(meta)}const body=document.createElement('div');body.className='page-body';p.appendChild(body);const num=document.createElement('div');num.className='page-number';num.textContent=index+1;p.appendChild(num);return p}
function captureSelection(id){const ta=document.querySelector(`[data-block-id="${id}"] .block-content`);return ta?{start:ta.selectionStart,end:ta.selectionEnd,scroll:ta.scrollTop}:null}
function renderPages(preserveId=focusedBlockId,selection=null){const stack=document.getElementById('pageStack');stack.innerHTML='';let page=pageTemplate(0),body=page.querySelector('.page-body');stack.appendChild(page);let pageIndex=0;state.blocks.forEach(b=>{const el=makeBlock(b);body.appendChild(el);autoResize(el.querySelector('textarea'));if(body.scrollHeight>body.clientHeight+1&&body.children.length>1){body.removeChild(el);pageIndex++;page=pageTemplate(pageIndex);body=page.querySelector('.page-body');stack.appendChild(page);body.appendChild(el);autoResize(el.querySelector('textarea'))}});if(!state.blocks.length){page.classList.add('page-empty');const first=addBlock('scene','');renderPages(first);return}renderPageNumbers();renderMeta();renderScenes();if(preserveId){setTimeout(()=>{const ta=document.querySelector(`[data-block-id="${preserveId}"] .block-content`);if(ta){ta.focus();if(selection){ta.setSelectionRange(Math.min(selection.start,ta.value.length),Math.min(selection.end,ta.value.length));ta.scrollTop=selection.scroll}else{ta.setSelectionRange(ta.value.length,ta.value.length)}}},0)}}
function renderPageNumbers(){document.querySelectorAll('.page-number').forEach((n,i)=>n.textContent=i+1)}
function queuePagination(id){cancelAnimationFrame(paginationFrame);paginationFrame=requestAnimationFrame(()=>{const ta=document.querySelector(`[data-block-id="${id}"] .block-content`);const body=ta?.closest('.page-body');if(!body)return;if(body.scrollHeight>body.clientHeight+1){const sel=captureSelection(id);renderPages(id,sel)}})}
function renderScenes(){const list=document.getElementById('sceneList');const scenes=state.blocks.filter(b=>b.type==='scene');list.innerHTML='';scenes.forEach((s,i)=>{const item=document.createElement('div');item.className='scene-item';item.dataset.id=s.id;item.innerHTML=`<span class="scene-no">${String(i+1).padStart(2,'0')}</span><span class="scene-text">${escapeHtml(s.text||'(ಹೊಸ ದೃಶ್ಯ)')}</span>`;item.onclick=()=>{const el=document.querySelector(`[data-block-id="${s.id}"]`);el?.scrollIntoView({behavior:'smooth',block:'center'});el?.querySelector('textarea')?.focus()};list.appendChild(item)})}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setActiveType(type){document.querySelectorAll('.format-btn,.type-card').forEach(x=>x.classList.toggle('active',x.dataset.type===type))}
function handleKey(e,id,ta){const b=state.blocks.find(x=>x.id===id);if(!b)return;if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();const id2=addBlock(NEXT[b.type]||'action','',id);renderPages(id2);return}if(e.key==='Tab'){e.preventDefault();const i=BLOCK_TYPES.indexOf(b.type),ni=e.shiftKey?(i-1+BLOCK_TYPES.length)%BLOCK_TYPES.length:(i+1)%BLOCK_TYPES.length;updateBlock(id,{type:BLOCK_TYPES[ni]});const sel={start:ta.selectionStart,end:ta.selectionEnd};renderPages(id,sel);return}if(e.key==='Backspace'&&ta.value===''){e.preventDefault();const p=before(id);removeBlock(id);if(!state.blocks.length)addBlock('scene','');renderPages(p);return}if(e.ctrlKey||e.metaKey){const m={'1':'scene','2':'action','3':'character','4':'dialogue','5':'parenthetical','6':'transition'};if(m[e.key]){e.preventDefault();updateBlock(id,{type:m[e.key]});renderPages(id);return}if(e.key.toLowerCase()==='s'){e.preventDefault();saveToStorage();return}if(e.key.toLowerCase()==='d'){e.preventDefault();downloadScript();return}}}
function chooseType(type){if(!focusedBlockId){const id=addBlock(type,'');renderPages(id);return}updateBlock(focusedBlockId,{type});renderPages(focusedBlockId)}
function toJSON(){return JSON.stringify({version:2,title:state.title,author:state.author,savedAt:new Date().toISOString(),blocks:state.blocks},null,2)}
function fromJSON(json){const d=JSON.parse(json);state.title=d.title||'ಅಶೀರ್ಷಿಕೆ';state.author=d.author||'';state.blocks=Array.isArray(d.blocks)?d.blocks:[];const seen=new Set();let max=0;state.blocks.forEach(b=>{let n=parseInt(String(b.id).replace(/\D/g,''),10);if(!isNaN(n))max=Math.max(max,n);if(seen.has(b.id)){b.id='b'+(++max)}seen.add(b.id);b.type=BLOCK_TYPES.includes(b.type)?b.type:'action';b.text=String(b.text||'')});state.idSeq=max;state.dirty=false;document.getElementById('titleInput').value=state.title;renderPages();}
function saveToStorage(){const key=state.currentScriptKey||'wb_'+Date.now();state.currentScriptKey=key;localStorage.setItem(key,toJSON());let keys=JSON.parse(localStorage.getItem('wb_index')||'[]').filter(k=>k!==key);keys.unshift(key);localStorage.setItem('wb_index',JSON.stringify(keys));state.dirty=false;renderMeta();showToast('ಉಳಿಸಲಾಗಿದೆ ✓')}
function loadFromStorage(key){const raw=localStorage.getItem(key);if(!raw)return;fromJSON(raw);state.currentScriptKey=key;state.dirty=false;hide('openOverlay');showToast('Script loaded ✓')}
function deleteFromStorage(key){localStorage.removeItem(key);localStorage.setItem('wb_index',JSON.stringify(JSON.parse(localStorage.getItem('wb_index')||'[]').filter(k=>k!==key)));renderOpenList()}
function renderOpenList(){const box=document.getElementById('savedScriptsList');const keys=JSON.parse(localStorage.getItem('wb_index')||'[]');box.innerHTML='';if(!keys.length){box.innerHTML='<div style="color:#737b83;font-size:11px;padding:12px 0">No saved scripts yet.</div>';return}keys.forEach(k=>{try{const d=JSON.parse(localStorage.getItem(k));const row=document.createElement('div');row.className='saved-item';row.innerHTML=`<div><b>${escapeHtml(d.title||'ಅಶೀರ್ಷಿಕೆ')}</b><br><small>${new Date(d.savedAt).toLocaleString('en-IN')}</small></div><button data-del="${k}">Delete</button>`;row.onclick=e=>{if(e.target.dataset.del)return;loadFromStorage(k)};row.querySelector('button').onclick=e=>{e.stopPropagation();deleteFromStorage(k)};box.appendChild(row)}catch{}})}
function uploadScript(file){const r=new FileReader();r.onload=e=>{try{fromJSON(e.target.result);state.currentScriptKey=null;hide('openOverlay');showToast('Loaded ✓')}catch{alert('Invalid .wbs file')}};r.readAsText(file)}
function downloadScript(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([toJSON()],{type:'application/json'}));a.download=(state.title||'screenplay').replace(/[^\p{L}\p{N}\s-]/gu,'').trim()+'.wbs';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(a.href);state.dirty=false;renderMeta();showToast('Downloaded .wbs ✓')}
function newScript(){if(state.dirty&&!confirm('Unsaved changes exist. Start a new script?'))return;state={title:'ಅಶೀರ್ಷಿಕೆ',author:'',blocks:[],idSeq:0,dirty:false,currentScriptKey:null};document.getElementById('titleInput').value=state.title;addBlock('scene','');renderPages(state.blocks[0].id);showToast('ಹೊಸ script ✓')}
function scheduleAutosave(){clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>{if(state.dirty)saveToStorage()},AUTOSAVE)}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1600)}
function show(id){document.getElementById(id).classList.add('visible')}function hide(id){document.getElementById(id).classList.remove('visible')}
function exportDocx(){if(!window.docx){alert('Word export library unavailable.');return}const {Document,Paragraph,TextRun,Packer,AlignmentType,PageBreak}=docx;const children=[];state.blocks.forEach(b=>{const text=b.text||'';let opts={children:[new TextRun({text,font:'Noto Sans Kannada',size:22,bold:b.type==='scene'||b.type==='character'})]};if(b.type==='character'){opts.alignment=AlignmentType.CENTER;opts.indent={left:2160}}if(b.type==='dialogue'){opts.indent={left:1080,right:1080}}if(b.type==='parenthetical'){opts.indent={left:1440,right:1440};opts.children=[new TextRun({text,italics:true,font:'Noto Sans Kannada',size:20})]}if(b.type==='transition')opts.alignment=AlignmentType.RIGHT;children.push(new Paragraph(opts))});const doc=new Document({sections:[{properties:{page:{margin:{top:1440,bottom:1440,left:1440,right:1440}}},children}]});Packer.toBlob(doc).then(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.title||'screenplay')+'.docx';a.click();URL.revokeObjectURL(a.href);showToast('Word downloaded ✓')})}
function init(){addBlock('scene','');renderPages(state.blocks[0].id);document.getElementById('titleInput').addEventListener('input',e=>{state.title=e.target.value;const p=document.getElementById('pageTitleInput');if(p)p.value=state.title;state.dirty=true;renderMeta();scheduleAutosave()});document.getElementById('btnNew').onclick=newScript;document.getElementById('btnSave').onclick=saveToStorage;document.getElementById('btnDownload').onclick=downloadScript;document.getElementById('btnDocx').onclick=exportDocx;document.getElementById('btnExport').onclick=()=>window.print();document.getElementById('btnShortcuts').onclick=()=>show('shortcutOverlay');document.getElementById('btnCloseShortcuts').onclick=()=>hide('shortcutOverlay');document.getElementById('btnOpen').onclick=()=>{renderOpenList();show('openOverlay')};document.getElementById('btnCloseOpen').onclick=()=>hide('openOverlay');document.getElementById('btnUploadFile').onclick=()=>document.getElementById('fileInput').click();document.getElementById('fileInput').onchange=e=>e.target.files[0]&&uploadScript(e.target.files[0]);document.getElementById('btnAddScene').onclick=()=>{const id=addBlock('scene','');renderPages(id);};document.querySelectorAll('.format-btn,.type-card').forEach(b=>b.onclick=()=>chooseType(b.dataset.type));document.getElementById('btnFocus').onclick=()=>document.body.classList.toggle('focus-mode');document.getElementById('btnCloseTools').onclick=()=>document.getElementById('toolsSidebar').style.display='none';document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelectorAll('.overlay.visible').forEach(x=>x.classList.remove('visible'))}});window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});renderMeta();scheduleAutosave()}
document.addEventListener('DOMContentLoaded',init);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
